### ISSUE TITLE
No 'Access-Control-Allow-Origin' header

### ISSUE THREAD

**Issue by filipzava** [GeoSmartCity-CIP/crowd-sourcing#3]
The respond header should have this attribute:
`Access-Control-Allow-Origin: *`

**Comment by rszturc** [comment]
All responses contain the Access-Control-Allow-Origin header.

**Comment by filipzava** [comment]
XMLHttpRequest cannot load http://geo.mapshakers.com:8080/CrowsSourcing/config. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://geo.mapshakers.com:222' is therefore not allowed access. The response had HTTP status code 404.

 Access-Control-Allow-Origin: *

**Comment by filipzava** [comment]
thx, solved
